%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1024
image_height: 768
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 795.11588
   fy: 795.11588
   cx: 517.12973
   cy: 395.59665
